
[TOC]

## 传播错误
- 在函数出处理错误
- 将错误返回给调用者
-   ```rust
    use std::fs::File;
    use std::io;
    use std::io::Read;

    fn read_username_from_file() -> Result<String, io::Error> {
        let f = File::open("hello.txt");

        let mut f = match f {
            Ok(file) => file,
            Err(e) => return Err(e),
        };

        let mut s = String::new();
        // tjl 注意下面的返回
        match f.read_to_string(&mut s) {
            Ok(_) => Ok(s),
            Err(e) => Err(e),
        }
    }

    fn main() {
        let result = read_username_from_file();
    }
    ```


## ？运算符
- **?** 运算符：传播错误的一种快捷方式
-   ```rust
    use std::fs::File;
    use std::io;
    use std::io::Read;
    
    fn read_username_from_file() -> Result<String, io::Error> {
        let mut f = File::open("hello.txt")?;
        let mut s = String::new();
        f.read_to_string(&mut s)?;
        Ok(s)
    }
    ```
- 如果 Resut 是 Ok: Ok 中的值就是表达式的结果，然后继续执行程序
- 如果 Result 是 Err: Err 就是整个函数的返回值，就像使用了 return
 

## ？与from 函数 
- `Trait std::convert::From` 上的 from 函数；
  - 用于错误之间的转换；
- 被 **?** 所应用的错误，会隐式的被 from 函数处理；
- 当 **?** 调用 **from** 函数时：
  - 它所接收的错误类型会被转化为当前函数返回类型所定义的错误类型
